version: "3.9"

services:
  web:
    user: root
    build:
      context: .
      dockerfile: Dockerfile-web
    image: my-jitsi-web:latest
    restart: unless-stopped
    ports:
      - "8080:80"   # Host port 8080 -> container port 80
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      # OPTIONAL (dev only): mount jitsi-meet for live edits - comment out for production
      # - ./jitsi-meet:/usr/share/jitsi-meet:Z
    environment:
      - ENABLE_XMPP_WEBSOCKET=${ENABLE_XMPP_WEBSOCKET}
      - ENABLE_AUTH=${ENABLE_AUTH}
      - ENABLE_GUESTS=${ENABLE_GUESTS}
      - PUBLIC_URL=${PUBLIC_URL}
      - ENABLE_LETSENCRYPT=${ENABLE_LETSENCRYPT}
      - LETSENCRYPT_DOMAIN=${LETSENCRYPT_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - meet.jitsi
    depends_on:
      - prosody
      - jicofo
      - jvb

  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable}
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5280:5280"
      - "5347:5347"
    volumes:
      - ${CONFIG}/prosody:/config:Z
      - ./prosody-plugins-custom:/prosody-plugins-custom:ro
    environment:
      - ENABLE_AUTH=${ENABLE_AUTH}
      - ENABLE_GUESTS=${ENABLE_GUESTS}
      - AUTH_TYPE=${AUTH_TYPE}
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - XMPP_AUTH_DOMAIN=${XMPP_AUTH_DOMAIN}
      - XMPP_MUC_DOMAIN=${XMPP_MUC_DOMAIN}
      - XMPP_INTERNAL_MUC_DOMAIN=${XMPP_INTERNAL_MUC_DOMAIN}
      - XMPP_BOSH_URL_BASE=${XMPP_BOSH_URL_BASE}
      - XMPP_WEBSOCKET_URL=${XMPP_WEBSOCKET_URL}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JICOFO_AUTH_DOMAIN=${JICOFO_AUTH_DOMAIN}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JWT_APP_ID=${JWT_APP_ID}
      - JWT_APP_SECRET=${JWT_APP_SECRET}
      - JWT_ALLOW_EMPTY=${JWT_ALLOW_EMPTY}
      - JWT_AUTH_TYPE=${JWT_AUTH_TYPE}
      - JWT_CLAIM_MODERATOR=${JWT_CLAIM_MODERATOR}
    networks:
      meet.jitsi:
        aliases:
          - prosody
          - ${XMPP_SERVER:-xmpp.meet.jitsi}

  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-stable}
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    environment:
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JICOFO_AUTH_DOMAIN=${JICOFO_AUTH_DOMAIN}
      - ENABLE_AUTH=${ENABLE_AUTH}
      - AUTH_TYPE=${AUTH_TYPE}

      - JICOFO_ENABLE_HEALTH_CHECKS=true
      - JICOFO_MAX_INACTIVE_ENDPOINTS=0
    depends_on:
      - prosody
    networks:
      - meet.jitsi

  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable}
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
      - "8081:8080"
    volumes:
      - ${CONFIG}/jvb:/config:Z
    environment:
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_STUN_SERVERS=${JVB_STUN_SERVERS}
      - JVB_AUTH_DOMAIN=${JVB_AUTH_DOMAIN}
      - JVB_PORT=${JVB_PORT}
      - JVB_COLIBRI_PORT=${JVB_COLIBRI_PORT}
    depends_on:
      - prosody
    networks:
      - meet.jitsi

networks:
  meet.jitsi:
    driver: bridge
